//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Id { get; set; }
        public int Id_product { get; set; }
        public int Id_user { get; set; }
        public int Count { get; set; }

        public override string ToString()
        {
            return $"id={Id}, id_product={Id_product}, id_user={Id_user}, count={Count}";
        }

        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
