//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.DateTime Date_add { get; set; }
        public int Id_product { get; set; }
        public int Id_user { get; set; }
        public string Text { get; set; }

        public override string ToString()
        {
            return $"id={Id}, date_add={Date_add}, id_product={Id_product}, id_user={Id_user}, text={Text}";
        }

        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
