//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_shop { get; set; }
        public string State { get; set; }
        public int Id_product { get; set; }
        public int Id_user { get; set; }
        public int Count { get; set; }
        public string Comment { get; set; }

        public override string ToString()
        {
            return $"id={Id}, date_start={Date_start}, date_shop={Date_shop}, state={State}, id_product={Id_product}, id_user={Id_user}, count={Count}, comment={Comment}";
        }

        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }
    }
}
