//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_brand
    {
        public int Id { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<int> Id_brand { get; set; }

        public override string ToString()
        {
            return $"id={Id}, id_product={Id_product}, id_brand={Id_brand}";
        }

        public virtual Brand Brand { get; set; }
        public virtual Product Product { get; set; }
    }
}
