//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Basket = new HashSet<Basket>();
            this.Comment = new HashSet<Comment>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date_reg { get; set; }
        public int Id_Role { get; set; }
        public string State { get; set; }
        public string Fio { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Number_credit_card { get; set; }
        public string Short_info { get; set; }
        public string Photo { get; set; }

        public override string ToString()
        {
            return $"id={Id}, date_reg={Date_reg}, id_role={Id_Role}, state={State}, fio={Fio}, login={Login}, email={Email}, password={Password}, phone={Phone}, address={Address}, " +
                $"city={City}, country={Country}, number_credit_card={Number_credit_card}, short_info={Short_info}, photo={Photo}";
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
